In [2]:
import numpy as np

In [3]:
x=np.linspace(start=10,stop=100,num=10)
print('x: ',x)
print('shape: ',x.shape)

x:  [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
shape:  (10,)


In [4]:
#extração de elementos
print('x: ',x)
print('Primeiro elemento',x[0])
print('Segundo elemento',x[1])
print('Ultimo elemento',x[9])
print('Ultimo elemento ',x[-1])

x:  [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
Primeiro elemento 10.0
Segundo elemento 20.0
Ultimo elemento 100.0
Ultimo elemento  100.0


In [6]:
#slicing
print('x: ',x)
print('Dois primeiros elementos: ', x[0:2])
print('Dois primeiros elementos: ',x[:2])
print('Dois ultimos elementos:',x[-2:])

x:  [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
Dois primeiros elementos:  [10. 20.]
Dois primeiros elementos:  [10. 20.]
Dois ultimos elementos: [ 90. 100.]


In [7]:
#slicing em arrays 2d
x=x.reshape(2,5)
print('x: ',x)

x:  [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [10]:
#extração de elementos
print('x: ',x)
print('Primeira linha e segunda coluna: ', x[0,1])
print('segunda linha e penultima coluna: ', x[1,-2])
print('Ultima linha e ultima coluna: ', x[-1,-1])

x:  [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]
Primeira linha e segunda coluna:  20.0
segunda linha e penultima coluna:  90.0
Ultima linha e ultima coluna:  100.0


In [13]:
#slicing: extração de subarrays
print('primeira linha inteira',x[0, :])
print('primeira linha, segunda a quarta coluna,', x[0, 1:4])
print('ultima coluna inteira',x[ :,[-1]])

primeira linha inteira [10. 20. 30. 40. 50.]
primeira linha, segunda a quarta coluna, [20. 30. 40.]
ultima coluna inteira [[ 50.]
 [100.]]


In [41]:
#slicing compartilha memoria
x=np.array([1,2,3])
print('x antes: ',x)
y=x[:2]
y[0]=-100
print(x)

x antes:  [1 2 3]
[-100    2    3]


In [43]:
#comando copy
x=np.array([1,2,3])
print('x antes: ',x)
y=x[:2].copy()
y[0]=-100
print(x)
print(y)

x antes:  [1 2 3]
[1 2 3]
[-100    2]
