In [1]:
import numpy as np

In [2]:
x=np.array([[1,3,7],[4,11,21],[42,8,9]])
print('x: ',x)

x:  [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [3]:
#reshape transforma a matriz em um vetor coluna
print(x.reshape(9,1))

[[ 1]
 [ 3]
 [ 7]
 [ 4]
 [11]
 [21]
 [42]
 [ 8]
 [ 9]]


In [4]:
#transposição de matriz
print('x transposta: ',x.T)

x transposta:  [[ 1  4 42]
 [ 3 11  8]
 [ 7 21  9]]


In [6]:
#np.sum: soma em um dado eixo, axis=0 linha, axis=1 coluna
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

106
[47 22 37]
[11 36 59]


In [7]:
#np.mean: media de um dado eixo
print(np.mean(x))
print(np.mean(x,axis=0))
print(np.mean(x,axis=1))

11.777777777777779
[15.66666667  7.33333333 12.33333333]
[ 3.66666667 12.         19.66666667]


In [10]:
#np.where, identificação dos indices onde uma dada condição é atendida
cond=x%2==0
print(cond)
i,j=np.where(cond)
print('indice i: linhas: ',i)
print('indice j: colunas:',j)
print(len(x[cond]))

[[False False False]
 [ True False False]
 [ True  True False]]
indice i: linhas:  [1 2 2]
indice j: colunas: [0 0 1]
3


In [12]:
cond=x%2==0
print(cond)
i_row=np.where(np.sum(cond,axis=1))[0]
print(i_row)
print(x[i_row, :])

[[False False False]
 [ True False False]
 [ True  True False]]
[1 2]
[[ 4 11 21]
 [42  8  9]]
