In [2]:
import numpy as np

In [3]:
x=np.array([[1,2],[3,4]])
y=np.array([1.5,3.5])
print('x: \n',x)
print('y: \n',y)

x: 
 [[1 2]
 [3 4]]
y: 
 [1.5 3.5]


In [7]:
print('print x<y: ',x>y)#broadcasting
print('print x<2: ',x<2)

print x<y:  [[False False]
 [ True  True]]
print x<2:  [[ True False]
 [False False]]


In [8]:
#indexação booleana
x=np.array([[1,3,7],
           [4,11,21],
           [42,9,8]])
print('x: \n',x)

x: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  9  8]]


In [9]:
#filtro
k=10
cond=x>k
print('condição: ',cond)
print(f'elementos maiores que {k} :',x[cond])
print(f'numero de elementos maiores que {k}: ',len(x[cond]))

condição:  [[False False False]
 [False  True  True]
 [ True False False]]
elementos maiores que 10 : [11 21 42]
numero de elementos maiores que 10:  3


In [10]:
cond=x%2==0
print('condição: ',cond)
print('numeros pares: ',x[cond])

condição:  [[False False False]
 [ True False False]
 [ True False  True]]
numeros pares:  [ 4 42  8]
