In [2]:
import numpy as np
np.array?

In [3]:
#CRIANDO ARRAY 1D
l=[1,2,3]
x=np.array(l)
print("x = ",x)
print("shape = ", x.shape)

x =  [1 2 3]
shape =  (3,)


In [5]:
#CRIANDO ARRAY 2D
l=[[1,2,3],[4,5,6]]
x=np.array(l)
print("x \n",x)
print("shape = ", x.shape)

x 
 [[1 2 3]
 [4 5 6]]
shape =  (2, 3)


In [7]:
#criando array 3d
l=[[1,2],[3,4],[5,6]] 
x=np.array(l)
print("x \n",x)
print("shape = ",x.shape)

x 
 [[1 2]
 [3 4]
 [5 6]]
shape =  (3, 2)


In [8]:
#criando arrays apenas co 0's
dim=(3,2)
x=np.zeros(dim)
print("x: ",x)
print("shape = ",x.shape)

x:  [[0. 0.]
 [0. 0.]
 [0. 0.]]
shape =  (3, 2)


In [9]:
#criando arrays apenas com 1's
dum=(3,3)
x=np.ones(dum)
print("x: ",x)
print("shape: ",x.shape)

x:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
shape:  (3, 3)


In [14]:
np.linspace?

In [15]:
#criando valores dentro de um intervalo
x_min,x_max=5,15
x=np.linspace(start=x_min,stop=x_max,num=6)
print("x =",x)
print("shape: ",x.shape)

x = [ 5.  7.  9. 11. 13. 15.]
shape:  (6,)


In [16]:
#criação da matriz identidade
n=4
x=np.eye(n)
print("x: ",x)
print("shape: ",x.shape)

x:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
shape:  (4, 4)


In [17]:
#criação de valores aleatorios
#np.random.seed(10)
x=np.random.random(size=(2,3))
print("x: ",x)
print("shape: ",x.shape)

x:  [[0.89289992 0.27269272 0.10125331]
 [0.40561069 0.8045153  0.86326138]]
shape:  (2, 3)
