In [2]:
import numpy as np

In [25]:
x=np.ones((2,2))
y=np.eye(2)
print('x=  ',x)
print('y=  ',y)

x=   [[1. 1.]
 [1. 1.]]
y=   [[1. 0.]
 [0. 1.]]


In [6]:
print('soma de dois arrays: ',x+y)
print('soma com float/int:  ',x+2)#broadcasting

soma de dois arrays:  [[2. 1.]
 [1. 2.]]
soma com float/int:   [[3. 3.]
 [3. 3.]]


In [8]:
print('subtração de dois arrays: ',x-y)
print('subtração com float/int : ',x-2)#broadcasting

subtração de dois arrays:  [[0. 1.]
 [1. 0.]]
subtração com float/int :  [[-1. -1.]
 [-1. -1.]]


In [9]:
print('divisao de dois arrays \n',x/y)
print('divisao com float/int \n',x/2)#broadcasting

divisao de dois arrays 
 [[ 1. inf]
 [inf  1.]]
divisao com float/int 
 [[0.5 0.5]
 [0.5 0.5]]


<ipython-input-9-63a275b94698>:1: RuntimeWarning: divide by zero encountered in true_divide
  print('divisao de dois arrays \n',x/y)


In [10]:
#quando o broadcasting nao funciona
np.array([1,2,3])+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [11]:
#combinação de operações
print('combinação de operações: \n',(x+y)/(x-2))

combinação de operações: 
 [[-2. -1.]
 [-1. -2.]]


#multiplicação
print('multiplicação de arrays: \n',x*y)
print('multiplicação usando float/int: \n',x*2)

In [13]:
#multiplicação
print('multiplicação de arrays: \n',x*y)
print('multiplicação usando float/int: \n',x*2)

multiplicação de arrays: 
 [[1. 0.]
 [0. 1.]]
multiplicação usando float/int: 
 [[2. 2.]
 [2. 2.]]


In [14]:
#multiplicação matricial
print('multiplicação matricial usando (np.dot): \n',np.dot(x,y))
print('multiplicação matricial usando @: \n', x@y)
print('multiplicação matricial usando (x.dot(y)): \n', x.dot(y))

multiplicação matricial usando (np.dot): 
 [[1. 1.]
 [1. 1.]]
multiplicação matricial usando @: 
 [[1. 1.]
 [1. 1.]]
multiplicação matricial usando (x.dot(y)): 
 [[1. 1.]
 [1. 1.]]


In [24]:
'''
Solução de um sistema de equações:
a+2*b=7
3*a-2*n=-11
Ax=c, onde:
x=[a,b]
a=[1,2], [3,-2]
c=[7,-11]
solução númerica = x=inv(a).c,
'''
a=np.array([[1,2],[3,-2]])
c=np.array([[7],[-11]])
x=np.dot(np.linalg.inv(a),c)
print('a,b = :',x.ravel())

a,b = : [-1.  4.]
